version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: pipenv run pytest -vv
    volumes:
      - ./src:/app
    env_file:
      - env_conf/.env
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    expose:
      - 5432
