version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: pipenv run uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./src:/app
    env_file:
      - env_conf/.env
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    expose:
      - 5432

volumes:
  db_data:
